import React, { useState, useEffect, useRef, useMemo } from 'react';
import { createPortal } from 'react-dom';
import { motion, AnimatePresence } from 'framer-motion';
import Globe from 'react-globe.gl';
import { FiX, FiPlay, FiPause, FiChevronRight, FiChevronLeft } from 'react-icons/fi';
import { WiDaySunny, WiStrongWind, WiNightClear } from "react-icons/wi";

// ─── MOCK 3D DATA GENERATORS ───────────────────────────────────────────────
const genRandomData = (N, colorFn) => [...Array(N).keys()].map(() => ({
  lat: (Math.random() - 0.5) * 180,
  lng: (Math.random() - 0.5) * 360,
  weight: Math.random(),
  color: colorFn(),
}));

const genArcsData = (N) => [...Array(N).keys()].map(() => ({
  startLat: (Math.random() - 0.5) * 180,
  startLng: (Math.random() - 0.5) * 360,
  endLat: (Math.random() - 0.5) * 180,
  endLng: (Math.random() - 0.5) * 360,
  color: ['#0bf', '#0ff', '#88f'][Math.floor(Math.random() * 3)]
}));

// ─── STORY CONFIGURATION ───────────────────────────────────────────────────
// In a real app, this would be generated by AI based on live coordinates.
const STORIES = [
  {
    id: "heat",
    title: "Thermal Intel",
    headline: "Scorching Regions Detected",
    description: "Heat volumes are rising aggressively across the equator today. Extreme UV radiation expected until 16:00.",
    icon: WiDaySunny,
    color: "#fb923c",
    globeConfig: {
      arcsData: [],
      pointsData: genRandomData(300, () => ['#dc2626', '#fb923c', '#f87171'][Math.floor(Math.random()*3)]),
      pointAltitude: "weight",
      pointColor: "color",
      pointRadius: 1.5,
      cameraLat: 20,
      cameraLng: 0,
      cameraAlt: 1.5
    }
  },
  {
    id: "wind",
    title: "Atmospheric Flow",
    headline: "High-Altitude Jetstreams Active",
    description: "Strong cross-continental winds spotted. Gusts may reach up to 45km/h in coastal areas. Flight turbulence predicted.",
    icon: WiStrongWind,
    color: "#38bdf8",
    globeConfig: {
      pointsData: [],
      arcsData: genArcsData(80),
      arcColor: "color",
      arcDashLength: 0.4,
      arcDashGap: 0.2,
      arcDashAnimateTime: 1500,
      cameraLat: 45,
      cameraLng: -90,
      cameraAlt: 2
    }
  },
  {
    id: "night",
    title: "Nocturnal Shift",
    headline: "Clear Skies Tonight",
    description: "Temperatures will drop rapidly by 22:00. Excellent visibility for stargazing. No precipitation expected.",
    icon: WiNightClear,
    color: "#a78bfa",
    globeConfig: {
      arcsData: [],
      pointsData: genRandomData(200, () => '#a78bfa'),
      pointAltitude: 0.1,
      pointRadius: 0.5,
      cameraLat: -20,
      cameraLng: 130,
      cameraAlt: 1.8
    }
  }
];

const STORY_DURATION = 8000; // 8 seconds per slide

// ─── FULL-SCREEN HOLOSTORY PORTAL ─────────────────────────────────────────
function HoloStoryModal({ onClose }) {
  const [currentSlideIndex, setCurrentSlideIndex] = useState(0);
  const [progress, setProgress] = useState(0);
  const [isPlaying, setIsPlaying] = useState(true);
  const globeRef = useRef();
  
  const currentStory = STORIES[currentSlideIndex];

  // Rotate globe slightly on each frame
  useEffect(() => {
    if (!globeRef.current || !isPlaying) return;
    const controls = globeRef.current.controls();
    if (controls) {
      controls.autoRotate = true;
      controls.autoRotateSpeed = 0.5;
    }
  }, [globeRef.current, isPlaying]);

  // Adjust camera when slide changes
  useEffect(() => {
    if (globeRef.current) {
        globeRef.current.pointOfView({
            lat: currentStory.globeConfig.cameraLat,
            lng: currentStory.globeConfig.cameraLng,
            altitude: currentStory.globeConfig.cameraAlt
        }, 2000); // 2 second transition
    }
  }, [currentSlideIndex, currentStory]);

  // Handle Story Progress & Auto-Advance
  useEffect(() => {
    if (!isPlaying) return;
    
    let startTime = Date.now();
    let animationFrame;

    const updateProgress = () => {
      const elapsed = Date.now() - startTime;
      const newProgress = (elapsed / STORY_DURATION) * 100;
      
      if (newProgress >= 100) {
        if (currentSlideIndex < STORIES.length - 1) {
          setCurrentSlideIndex(prev => prev + 1);
        } else {
          // Loop back or close? Let's loop.
          setCurrentSlideIndex(0);
        }
        setProgress(0);
      } else {
        setProgress(newProgress);
        animationFrame = requestAnimationFrame(updateProgress);
      }
    };
    
    animationFrame = requestAnimationFrame(updateProgress);
    
    return () => cancelAnimationFrame(animationFrame);
  }, [currentSlideIndex, isPlaying]);

  // Navigation handlers
  const goToNext = () => {
      if (currentSlideIndex < STORIES.length - 1) setCurrentSlideIndex(p => p + 1);
      setProgress(0);
  };
  
  const goToPrev = () => {
      if (currentSlideIndex > 0) setCurrentSlideIndex(p => p - 1);
      setProgress(0);
  };

  return createPortal(
    <motion.div
      initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
      style={{ position: 'fixed', inset: 0, zIndex: 99999, background: '#030712' }}
    >
      {/* 3D GLOBE BACKGROUND */}
      <div style={{ position: 'absolute', inset: 0, opacity: 0.85 }}>
          <Globe
            ref={globeRef}
            globeImageUrl="//unpkg.com/three-globe/example/img/earth-dark.jpg"
            bumpImageUrl="//unpkg.com/three-globe/example/img/earth-topology.png"
            backgroundColor="rgba(0,0,0,0)"
            
            // Apply current story's data
            pointsData={currentStory.globeConfig.pointsData}
            pointAltitude={currentStory.globeConfig.pointAltitude}
            pointColor={currentStory.globeConfig.pointColor}
            pointRadius={currentStory.globeConfig.pointRadius}
            pointsMerge={true}
            
            arcsData={currentStory.globeConfig.arcsData}
            arcColor={currentStory.globeConfig.arcColor}
            arcDashLength={currentStory.globeConfig.arcDashLength}
            arcDashGap={currentStory.globeConfig.arcDashGap}
            arcDashAnimateTime={currentStory.globeConfig.arcDashAnimateTime}
          />
      </div>

      {/* GRADIENT OVERLAYS FOR READABILITY */}
      <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(180deg, rgba(3,7,18,0.9) 0%, rgba(3,7,18,0) 25%, rgba(3,7,18,0) 70%, rgba(3,7,18,0.95) 100%)', pointerEvents: 'none' }} />

      {/* STORY UI OVERLAY */}
      <div style={{ position: 'relative', zIndex: 10, width: '100%', height: '100%', display: 'flex', flexDirection: 'column', p: '20px', maxWidth: '600px', margin: '0 auto' }}>
          
          {/* Progress Bars */}
          <div style={{ display: 'flex', gap: '6px', paddingTop: '20px', paddingLeft: '20px', paddingRight: '20px' }}>
              {STORIES.map((_, idx) => (
                  <div key={idx} style={{ flex: 1, height: '4px', background: 'rgba(255,255,255,0.2)', borderRadius: '2px', overflow: 'hidden' }}>
                      <div style={{ 
                          height: '100%', 
                          background: '#fff', 
                          width: idx < currentSlideIndex ? '100%' : idx === currentSlideIndex ? `${progress}%` : '0%',
                          transition: 'width 0.1s linear'
                      }} />
                  </div>
              ))}
          </div>

          {/* Header */}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '16px 20px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                  <div style={{ background: 'rgba(255,255,255,0.1)', backdropFilter: 'blur(10px)', padding: '6px 12px', borderRadius: '99px', border: '1px solid rgba(255,255,255,0.15)', color: '#fff', fontSize: '0.75rem', fontWeight: '800', letterSpacing: '0.05em', textTransform: 'uppercase', display: 'flex', alignItems: 'center', gap: '6px' }}>
                      <currentStory.icon size={16} color={currentStory.color} />
                      {currentStory.title}
                  </div>
              </div>
              <div style={{ display: 'flex', gap: '10px' }}>
                  <button onClick={() => setIsPlaying(!isPlaying)} style={{ background: 'rgba(255,255,255,0.1)', border: 'none', borderRadius: '50%', width: '36px', height: '36px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', cursor: 'pointer', backdropFilter: 'blur(8px)' }}>
                      {isPlaying ? <FiPause size={16} /> : <FiPlay size={16} />}
                  </button>
                  <button onClick={onClose} style={{ background: 'rgba(255,255,255,0.1)', border: 'none', borderRadius: '50%', width: '36px', height: '36px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', cursor: 'pointer', backdropFilter: 'blur(8px)' }}>
                      <FiX size={18} />
                  </button>
              </div>
          </div>

          {/* Invisible interactive zones for Tap to advance */}
          <div style={{ flex: 1, display: 'flex' }}>
              <div onClick={goToPrev} style={{ flex: 1, cursor: 'w-resize' }} />
              <div onClick={goToNext} style={{ flex: 1, cursor: 'e-resize' }} />
          </div>

          {/* Story Text Container */}
          <AnimatePresence mode="wait">
              <motion.div 
                  key={currentSlideIndex}
                  initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -20 }} transition={{ duration: 0.4 }}
                  style={{ padding: '0 24px 40px 24px', pointerEvents: 'none' }}
              >
                  <motion.h2 
                      initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.2 }}
                      style={{ fontSize: '3rem', fontWeight: '900', color: '#fff', lineHeight: '1.1', marginBottom: '16px', textShadow: '0 4px 20px rgba(0,0,0,0.5)' }}
                  >
                      {currentStory.headline}
                  </motion.h2>
                  <motion.p 
                      initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.4 }}
                      style={{ fontSize: '1.1rem', color: 'rgba(255,255,255,0.85)', lineHeight: '1.5', fontWeight: '500', maxWidth: '90%', textShadow: '0 2px 10px rgba(0,0,0,0.5)' }}
                  >
                      {currentStory.description}
                  </motion.p>
              </motion.div>
          </AnimatePresence>
      </div>
    </motion.div>,
    document.body
  );
}

// ─── HOLOSTORY PREVIEW CARD ───────────────────────────────────────────────
export default function HoloStoryCard({ onDismiss }) {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <>
      <motion.div
        initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.4, type: 'spring', bounce: 0.3 }}
        onClick={() => setIsOpen(true)}
        style={{ height: '240px', borderRadius: '24px', overflow: 'hidden', position: 'relative', cursor: 'pointer', border: '1px solid rgba(255,255,255,0.1)', boxShadow: '0 12px 40px rgba(0,0,0,0.5)', background: '#030712' }}
      >
        {/* Abstract 3D preview visualization (CSS only mapping) */}
        <div style={{ position: 'absolute', inset: 0, overflow: 'hidden' }}>
            <div style={{ position: 'absolute', top: '-50%', left: '-20%', width: '150%', height: '200%', background: 'radial-gradient(circle at center, rgba(56,189,248,0.15) 0%, transparent 60%)', filter: 'blur(40px)', animation: 'pulse 6s infinite alternate' }} />
            <div style={{ position: 'absolute', bottom: '-40%', right: '-20%', width: '120%', height: '150%', background: 'radial-gradient(circle at center, rgba(167,139,250,0.15) 0%, transparent 60%)', filter: 'blur(30px)', animation: 'pulse 8s infinite alternate-reverse' }} />
            
            {/* Grid wireframe simulation */}
            <div style={{ position: 'absolute', inset: 0, backgroundImage: 'linear-gradient(rgba(255,255,255,0.03) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.03) 1px, transparent 1px)', backgroundSize: '24px 24px', transform: 'perspective(500px) rotateX(60deg) scale(2)', transformOrigin: 'bottom center', opacity: 0.5 }} />
        </div>

        {/* Card Content Overlay */}
        <div style={{ position: 'absolute', inset: 0, zIndex: 2, display: 'flex', flexDirection: 'column', justifyContent: 'space-between', padding: '24px' }}>
          
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
            <div style={{ background: 'rgba(255,255,255,0.1)', backdropFilter: 'blur(10px)', padding: '6px 14px', borderRadius: '99px', border: '1px solid rgba(255,255,255,0.15)', color: '#fff', fontSize: '0.65rem', fontWeight: '800', letterSpacing: '0.08em', textTransform: 'uppercase' }}>
              SkySight Intel
            </div>

            {onDismiss && (
              <motion.button whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.9 }}
                onClick={(e) => { e.stopPropagation(); onDismiss(); }}
                style={{ background: 'rgba(255,255,255,0.08)', border: 'none', borderRadius: '50%', width: '32px', height: '32px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', cursor: 'pointer' }}>
                <FiX size={14} />
              </motion.button>
            )}
          </div>

          <div>
             <h3 style={{ margin: 0, fontSize: '1.8rem', fontWeight: '900', color: '#fff', letterSpacing: '-0.02em', lineHeight: '1.1' }}>
                The Daily<br/>Weather Story
             </h3>
             <p style={{ margin: '8px 0 0 0', fontSize: '0.85rem', color: 'rgba(255,255,255,0.6)', fontWeight: '500' }}>
                 Tap to launch volumetric analysis.
             </p>
          </div>
        </div>
      </motion.div>

      <AnimatePresence>
        {isOpen && <HoloStoryModal onClose={() => setIsOpen(false)} />}
      </AnimatePresence>
    </>
  );
}
